import React from 'react'
import Head from 'next/head'
import Styles from '../styles/About.module.css'
import Gallery from '../components/About/Gallery'


const About = () => {




  return (
    <>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
          <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
          <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
          <link rel="manifest" href="/site.webmanifest" />
        </Head>    
        <div className={Styles.container}>

          <h1 className={Styles.h1}>
            Rólunk
          </h1>

          <div  className={Styles.P_Container}>
            <p>Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque.Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque. Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque. Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque.Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque. Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque. </p>
            <p>Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque.Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque. Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque.</p>
            <p>Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque.Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque. Lorem ipsum dolor sit amet consectetur. Faucibus odio risus sed pretium magna duis neque.</p>
            <p>Lorem ipsum dolor sit amet consectetur. </p>
          </div>
          < Gallery />
        </div>
    </>


  )
}

export default About