import React from 'react'
import Head from 'next/head'
import Modal from '../components/Modal'


const About = () => {
  return (
    <>
        <Head>
          <title>Rólunk</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Modal />
    </>
  )
}

export default About