import React from 'react'
import Head from 'next/head'

const afesz = () => {
  return (
    <>
        <Head>
        <title>Áfész</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>afesz</div>
    </>
  )
}

export default afesz