import React from 'react'
import Head from 'next/head'

const faq = () => {
  return (
    <>
    <Head>
      <title>FAQ</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div>faq</div>
    </>
  )
}

export default faq