import React from 'react'
import Head from 'next/head'
import Styles from '../styles/Faq.module.css'
import Accordion from '../components/Faq/Accordion'


const Faq = () => {
  return (
    <>
    <Head>
      <title>Gyakran feltett kérdések</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <div className={Styles.container} >
      <h1 className={Styles.h1}>
            GYAKRAN FELTETT KÉRDÉSEK
      </h1>
        <div className={Styles.contentContainer}>
           <Accordion />
        </div>
      </div>
    </main>
    </>
  )
}

export default Faq