import { lazy } from 'react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../layouts/Header'
import Apartments from '../layouts/Apartments'
import Contact from '../layouts/Contact'
import Direction from '../layouts/Direction'
import ReviewPrefix from '../layouts/ReviewPrefix'

const inter = Inter({ subsets: ['latin'] })

// {isMobile ? <Reviews  /> : <NewReviewModule />}



export default function Home() {


  return (
    <>
      <Head>
        <title>Harmony Apartments </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>
      <Header />
      <main>
        <section>
          <Apartments />
        </section>
        <section>
          <ReviewPrefix />
        </section>
        <section>
         <Contact />
        </section>
        <section>
         <Direction />
        </section>
      </main>
    </>
  )
}

